[tool.poetry]
name = "ga"
version = "0.1.0"
description = ""
authors = ["JunYu <junkangrstt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tabulate = "^0.9.0"
matplotlib = "^3.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
